- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:
    ~/.aliases:
    ~/.antigenrc:

- shell:
  - git submodule sync --recursive
  - git submodule update --init --recursive
