- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:

- shell:
  - git submodule sync --recursive
  - git submodule update --init --recursive
