- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.vim:
    ~/.vimrc:
    ~/.zshrc:
    ~/.zsh_plugins.txt: zsh_plugins.txt

- shell:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - ./fonts/fonts/install.sh
