- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:
    ~/Library/Preferences/: iterm/com.googlecode.iterm2.plist

- shell:
  - git submodule sync --recursive
  - git submodule update --init --recursive
